# Generated by Django 2.1.4 on 2019-01-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'rooms',
            },
        ),
    ]
